### Smell configuration
detectors:
  IrresponsibleModule:
    enabled: false
  FeatureEnvy:
    enabled: false
  UtilityFunction:
    enabled: false

### Excluding directories

# Directories and files below will not be scanned at all
exclude_paths:
  - bin/
  - config/
  - log/
  - public/
  - vendor/
  - db/
  - spec/spec_helper.rb
  - spec/rails_helper.rb
